---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-server
spec:
  tls:
  - hosts:
    - jenkins.kronshtadt.ru
    secretName: jenkins
  rules:
    - host: jenkins.kronshtadt.ru
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: jenkins-server
                port:
                  number: 443
            path: /